"""
Script to generate weights for a e-ai model

Generate weights for a model generated with the renesas web compiler[1].
A guide on how-to use the webcompiler is available on [2].
The autogenerated weights from the e-ai webcompiler are not correct,
therefore they are converted by hand.
This is possible for a minimal model it is not possible for a complex model because there is
not much documentation rom renesas and only a minimal example documented.

However, with the new version (v.1.4.0) of the renesas webcompiler it is possible that this$
issues are fixed!

:Author: Raphael Zingg zing@zhaw.ch
:Copyright: 2020 ZHAW / Institute of Embedded Systems
:References:
 - [1] Renesas, Renesas Web Compiler, http://tool-cloud2.renesas.com/
 - [2] Renesas, E-AI translator tutorial,
       https://www.renesas.com/eu/en/products/gadget-renesas/boards/e-ai-translator-tutorial.html
"""
import numpy as np
import tensorflow as tf

# --------------------------------------------------------------------------------------------------
# write weights in renesas format
# --------------------------------------------------------------------------------------------------
model = tf.keras.models.load_model('../neural_networks/mnist_min.h5')
W = model.get_weights()
FP = 'target/Inc/weights.h'
with open(FP, 'w') as f:
    f.write('#ifndef WEIGHTS_H_\n#define WEIGHTS_H_\n')
    f.write('TPrecision ip1_weights[] = {')
    np.transpose(W[0]).tofile(f, sep=", ", format="%.12f")
    f.write('};\n')

    f.write('TPrecision ip1_biases[] = {')
    np.transpose(W[1]).tofile(f, sep=", ", format="%.12f")
    f.write('};\n')
    f.write('#endif\n')

print('\n\n Done \n\n')
